### ISSUE TITLE
Cannot find the entry in recommendations for current TDG

### ISSUE THREAD

**Issue by Abigiris** [JohnnyPeng18/HiTyper#3]
Hi, thanks for your tool to help me with type inference work.
I have successfully run HiTyper to generate some inferred types. But when I try to invoke Type4Py, some errors are reported:
`[Type Recommendation]Cannot find the entry in recommendations for current TDG funcname@classname`
I'm wondering if this error can be fixed? Or is this function unable to get type recommendations from Type4Py? Thank you.

**Comment by JohnnyPeng18** [comment]
Hi, thanks for your interest!
For this problem, please change `funcname@classname` to your own function name and class name. For example, `testfunc@testclass`. Using `global` as the class name if the function is a global function. Meanwhile, pls update your code by pulling the latest code since we have fixed a bug about reading the recommendations.
If this error still occurs after conducting the above actions, please leave your command and testfile.

**Comment by Abigiris** [comment]
I have updated my code,  but the error still exists.
I used some open source projects as test cases, one of which was from https://github.com/faif/python-patterns. For example, I wanted to infer the fucntion `__init__` of class `Catalog` in python-patterns/blob/master/patterns/behavioral/catalog.py, and I used the command:
`hityper infer -p python-patterns -l __init__@Catalog -d outputs -n 1 -t`
And the error report is:
`[Type Recommendation]Cannot find the entry in recommendations for current TDG __init__@Catalog`

Another question is that I only get `global@global` results in .json files when I use `hityper infer -p python-patterns -d outputs -n 1 -t`. How can I get the results of all the functions in the project?

Thanks for your reply.

**Comment by JohnnyPeng18** [comment]
Hi, We have fixed these two bugs. Pls pull the latest code to try again.

**Comment by Abigiris** [comment]
No errors were reported and the log shows that HiTyper successfully got some type recommendations from Type4Py. But these recommendations did not affect the result. The result is the same with or without `-t`.

**Comment by JohnnyPeng18** [comment]
Bug fixed, pls pull the latest code.

**Comment by alaalial** [comment]
is this considered an error  for example:
**"[WARNING] [Type Recommendation]Cannot get the recommended types for variable analyze or the recommended type set is empty. "**
 or is this because the tool can not infer all types because of the dynamic feature of python?

**Comment by JohnnyPeng18** [comment]
This is because Type4Py cannot give predictions for the variable. All warnings should not be considered errors. If you want to omit these warnings, just increase the log level to ERROR.

**Comment by alaalial** [comment]
thanks for your replay :

if I got for example:

[ERROR] [Type Recommendation]Cannot find the entry in recommendations for current TDG send_sqs_message@global

this error in the code or because of type4py

**Comment by JohnnyPeng18** [comment]
If this error occurs occasionally, just ignore it because type4py sometimes can fail to predict some functions.
